# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/olesyamartinyuk/PycharmProjects/database/design.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(815, 432)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 7, 1, 1)
        self.data_search = QtWidgets.QLineEdit(self.centralwidget)
        self.id = QtWidgets.QLineEdit(self.centralwidget )
        self.title = QtWidgets.QLineEdit(self.centralwidget)
        self.author = QtWidgets.QLineEdit(self.centralwidget)
        self.year = QtWidgets.QLineEdit(self.centralwidget)
        self.price = QtWidgets.QLineEdit(self.centralwidget)
        self.title.setObjectName("title")
        self.gridLayout.addWidget(self.title, 1, 5, 1, 1)
        self.button_export = QtWidgets.QPushButton(self.centralwidget)
        self.button_export.setObjectName("button_export")
        self.gridLayout.addWidget(self.button_export, 4, 0, 2, 2)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 3, 0, 1, 9)
        self.year.setObjectName("year")
        self.gridLayout.addWidget(self.year, 1, 7, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 8, 1, 1)
        self.button_delete_db = QtWidgets.QPushButton(self.centralwidget)
        self.button_delete_db.setObjectName("button_delete_db")
        self.gridLayout.addWidget(self.button_delete_db, 4, 7, 2, 2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 6, 1, 1)
        self.id.setObjectName("id")
        self.gridLayout.addWidget(self.id, 1, 4, 1, 1)
        self.button_backup = QtWidgets.QPushButton(self.centralwidget)
        self.button_backup.setObjectName("button_backup")
        self.gridLayout.addWidget(self.button_backup, 6, 0, 1, 4)
        self.button_add = QtWidgets.QPushButton(self.centralwidget)
        self.button_add.setObjectName("button_add")
        self.gridLayout.addWidget(self.button_add, 2, 4, 1, 5)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 4)
        self.author.setObjectName("author")
        self.gridLayout.addWidget(self.author, 1, 6, 1, 1)
        self.button_import = QtWidgets.QPushButton(self.centralwidget)
        self.button_import.setObjectName("button_import")
        self.gridLayout.addWidget(self.button_import, 4, 2, 2, 3)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 5, 1, 1)
        self.price.setObjectName("price")
        self.gridLayout.addWidget(self.price, 1, 8, 1, 1)
        self.data_search.setObjectName("data_search")
        self.gridLayout.addWidget(self.data_search, 1, 0, 1, 4)
        self.button_recover = QtWidgets.QPushButton(self.centralwidget)
        self.button_recover.setObjectName("button_recover")
        self.gridLayout.addWidget(self.button_recover, 6, 5, 1, 1)
        self.button_delete = QtWidgets.QPushButton(self.centralwidget)
        self.button_delete.setObjectName("button_delete")
        self.gridLayout.addWidget(self.button_delete, 2, 0, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 815, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Year"))
        self.button_export.setText(_translate("MainWindow", "Export to CSV"))
        self.label.setText(_translate("MainWindow", "ID"))
        self.label_5.setText(_translate("MainWindow", "Price"))
        self.button_delete_db.setText(_translate("MainWindow", "Delete database"))
        self.label_3.setText(_translate("MainWindow", "Author"))
        self.button_backup.setText(_translate("MainWindow", "Create back-up file"))
        self.button_add.setText(_translate("MainWindow", "Add new record"))
        self.label_6.setText(_translate("MainWindow", "Enter data to delete"))
        self.button_import.setText(_translate("MainWindow", "Import from CSV"))
        self.label_2.setText(_translate("MainWindow", "Title"))
        self.button_recover.setText(_translate("MainWindow", "Recover from back-up file"))
        self.button_delete.setText(_translate("MainWindow", "Delete"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
